# Generated by Django 4.0.5 on 2022-07-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
