# Generated by Django 4.0.5 on 2022-07-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usertype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'branch'), (2, 'officer'), (3, 'admin'), (4, 'superAdmin')]),
        ),
    ]
