# Generated by Django 4.0.5 on 2022-07-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'branch'), (2, 'officer'), (3, 'admin'), (4, 'access conrol admin'), (5, 'access control staff')]),
        ),
    ]
