# Generated by Django 4.0.5 on 2022-07-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprivilege',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
