# Generated by Django 4.0.5 on 2022-07-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_delete_requested',
            field=models.BooleanField(default=False),
        ),
    ]
