# Generated by Django 4.1.2 on 2022-10-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_branch_alter_user_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'branch'), (2, 'officer'), (3, 'admin'), (4, 'access control admin'), (5, 'access control staff')], null=True),
        ),
    ]
