# Generated by Django 4.1.2 on 2023-06-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat-images'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
