# Generated by Django 4.1.2 on 2023-06-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_conversation_remove_message_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
